<?php if ($block->isProductIntegrated()) { ?>
<div id="customers-canvas-content">
    <div id="customers-canvas-container">
        <div id="customers-canvas-editor-parent">
            <?= json_encode($block->isProductIntegrated()); ?>
        </div>

        <?php if (!$block->isPopupMode()) { ?>
            <div id="closebtn-wrapper">
                <span class="customers-canvas-closebtn" id="customers-canvas-closebtn">
                    &#706; <?= __('Back to product'); ?>
                </span>
            </div>
        <?php } ?>
    </div>
</div>
<div id="customers-canvas-shroud">
    <img class="customers-canvas-page-spinner" src="<?= $this->getViewFileUrl('Aurigma_CustomersCanvas::images/spinner-load.png'); ?>" alt="spinner" />
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Aurigma_CustomersCanvas/js/editor-view-helper": {},
            "Aurigma_CustomersCanvas/js/query-string-helper": {}
        },
        ".column.main": {
            "Aurigma_CustomersCanvas/js/editor-loader": {
                "pluginSettings": {
                    "customersCanvasBaseUrl": <?= json_encode($block->getBackOfficeUrl()); ?>,
                    "assetStorageUrl": <?= json_encode($block->getAssetStorageUrl()); ?>,
                    "assetProcessorUrl": <?= json_encode($block->getAssetProcessorUrl()); ?>,
                    "magentoBaseUrl": <?= json_encode($block->getBaseUrl()); ?>,
                    "language": <?= json_encode($block->getLanguage()); ?>,
                    "currency": <?= json_encode($block->getCurrency()); ?>,
                    "ecommerceSystemType": <?= json_encode($block->getEcommerceSystemType()); ?>,
                    "addToCartUrl": <?= json_encode($block->getAddToCartUrl()); ?>,
                    "addToCartUpdateUrl": <?= json_encode($block->getAddToCartUpdateUrl()); ?>,
                    "updatePriceUrl": <?= json_encode($block->getUpdatePriceUrl()); ?>,
                    "popupMode": <?= json_encode($block->isPopupMode()); ?>,
                    "redirectToCartAfterAdd": <?= json_encode($block->isRedirectToCartEnabled()); ?>
                },
                "userInfo": {
                    "id": <?= json_encode($block->getModifyCustomerId()); ?>,
                    "data": {
                        <?php if ($block->isLoggedIn()): ?>
                            "Your Name": <?= json_encode($block->getCustomerName()); ?>,
                            "Email": <?= json_encode($block->getCustomerEmail()); ?>
                        <?php endif; ?>
                    }
                },
                "commonSettings": {
                    "tenantId": <?= json_encode($block->getTenantId()); ?>,
                    "projectOptionKey": <?= json_encode($block->getProjectOptionKey()); ?>,
                    "isLoggedIn": <?= json_encode($block->isLoggedIn()); ?>
                },
                "productModel": {
                    "id": <?= json_encode($block->getProductId()); ?>,
                    "sku": <?= json_encode($block->getProductSku()); ?>,
                    "name": <?= json_encode($block->getProductName()); ?>,
                    "price": <?= json_encode($block->getProductPrice()); ?>,
                    "type_id": <?= json_encode($block->getProductType()); ?>,
                    "options": <?= json_encode($block->getProductOptions()); ?>,
                    "custom_attributes": <?= json_encode($block->getProductAttributes()); ?>
                }
            }
        },
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false,
                "customersCanvas": {
                    "pluginSettings": {
                        "customersCanvasBaseUrl": <?= json_encode($block->getBackOfficeUrl()); ?>,
                        "assetStorageUrl": <?= json_encode($block->getAssetStorageUrl()); ?>,
                        "assetProcessorUrl": <?= json_encode($block->getAssetProcessorUrl()); ?>,
                        "magentoBaseUrl": <?= json_encode($block->getBaseUrl()); ?>,
                        "language": <?= json_encode($block->getLanguage()); ?>,
                        "currency": <?= json_encode($block->getCurrency()); ?>,
                        "ecommerceSystemType": <?= json_encode($block->getEcommerceSystemType()); ?>,
                        "addToCartUrl": <?= json_encode($block->getAddToCartUrl()); ?>,
                        "addToCartUpdateUrl": <?= json_encode($block->getAddToCartUpdateUrl()); ?>,
                        "updatePriceUrl": <?= json_encode($block->getUpdatePriceUrl()); ?>,
                        "popupMode": <?= json_encode($block->isPopupMode()); ?>,
                        "redirectToCartAfterAdd": <?= json_encode($block->isRedirectToCartEnabled()); ?>
                    },
                    "userInfo": {
                        "id": <?= json_encode($block->getModifyCustomerId()); ?>,
                        "data": {
                            <?php if ($block->isLoggedIn()): ?>
                                "Your Name": <?= json_encode($block->getCustomerName()); ?>,
                                "Email": <?= json_encode($block->getCustomerEmail()); ?>
                            <?php endif; ?>
                        }
                    },
                    "commonSettings": {
                        "tenantId": <?= json_encode($block->getTenantId()); ?>,
                        "projectOptionKey": <?= json_encode($block->getProjectOptionKey()); ?>,
                        "isLoggedIn": <?= json_encode($block->isLoggedIn()); ?>
                    },
                    "productModel": {
                        "id": <?= json_encode($block->getProductId()); ?>,
                        "sku": <?= json_encode($block->getProductSku()); ?>,
                        "name": <?= json_encode($block->getProductName()); ?>,
                        "price": <?= json_encode($block->getProductPrice()); ?>,
                        "type_id": <?= json_encode($block->getProductType()); ?>,
                        "options": <?= json_encode($block->getProductOptions()); ?>,
                        "custom_attributes": <?= json_encode($block->getProductAttributes()); ?>
                    }
                }
            }
        }
    }        
</script>

<?php } ?>